type MarketCreated @entity(immutable: true) {
  id: Bytes!
  market: Bytes! # address
  lpToken: Bytes! # address
  questionId: Bytes! # bytes32
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type OwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
type MarketResolved @entity(immutable: true) {
  id: Bytes!
  questionId: Bytes! # bytes32
  roundId: BigInt! # uint80
  price: BigInt! # int256
  updatedAt: BigInt! # uint256
  yesWins: Int! # uint8
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}

type BinaryOracleOwnershipTransferred @entity(immutable: true) {
  id: Bytes!
  previousOwner: Bytes! # address
  newOwner: Bytes! # address
  blockNumber: BigInt!
  blockTimestamp: BigInt!
  transactionHash: Bytes!
}
